### ISSUE TITLE
pledge-CA certs endpoint handling

### ISSUE THREAD

**Issue by stfries** [anima-wg/anima-brski-prm#21]
The pledge-CAcerts endpoint on the pledge is intended to provide CA certificates. This endpoint needs specific consideration as the provisioning of CA certificates needs specific protection. While this is done in BRSKI by using the EST functionality, bound to the underlying TLS connection, it must be separately secured in BRSKI-PRM.

Proposal: Provide CA certificates as JSON object, signed by the registrar and only accept them on the pledge after successfully accepting the domain certificate. This allows the pledge to verify, that the CA certificates are provided in an authenticated and authorized way.

**Comment by EskoDijk** [comment]
Option 1: same Registrar resource /cacerts, and we define use of an additional media type 'signed JSON bag' for that resource. The Agent requests this type and gets the signed CA certs bag.

Option 2: new Registrar resource /cacertsX, supporting only the above 'signed JSON bag' media type. The Agent requests on this resource (with or without explicitly asking for the type) and gets the signed CA certs bag.

**Comment by EskoDijk** [comment]
The best / optimal procedure for using the CA-certs bag by Pledge & Agent should also be described.

Option A: Agent provides the CA-certs bag to Pledge *before* sending the LDevID cert to it. This may comply better with RFC 7030 and allows the Pledge to verify that the LDevID cert correctly chains to the Domain CA based on the "/cacerts response" before indicating a final success/fail for acceptance of the LDevID cert. Pledge MUST do this verification.

Option B: Agent provides it *after* the LDevID has been successfully accepted by the Pledge (with enroll-status indicating success). In this case the CA-certs isn't used to validate the LDevID cert at all, but used for future authentication of Registrars/Peers on the Domain e.g. when using TLS.

Option B.2 : As Option B, but Agent now optionally provides CA-certs bag to the Pledge. (Then Pledge may need some way to indicate if it needs it! Otherwise the Agent doesn't know.)  

(maybe more options)

**Comment by stfries** [comment]
Regarding option 1 and 2 for the endpoints on the Registrar, I would be in favor of option 2. The reason is that we defined an own endpoint to provide the JSON signed certification request (P10) to the registrar to indicate a different handling in the registrar side. This way it is clear what is expected at the specific endpoint.

**Comment by stfries** [comment]
Regarding options A/B/B.2, in any case, the pledge would need the voucher first to be able to verify the signature of the signed JSON CA-Certs bag. 

In general I like the flexibility of all 3 but option B.2 would most likely be the one that I had in mind. The reason is that we expected that the trust anchor in the voucher would also be used to sign the LDevIDs for the pledge. But this may be a restriction, so Option A would be the most flexible approach. 
Do you think it makes sense to state all 3 options with the respective considerations you provided?

**Comment by siethower** [comment]
From my point of view we should start with option A, as this should be easiest to implement without indicating the need for CA-certs, at least for none constrained environments. Situation and handling could be different for constraint environments, this my require option B.2.  
As current BRSKI-PRM is focusing on none constrained environments we should got for option A, but leave the door open for option 2.B as well.

**Comment by siethower** [comment]
Maybe also worth to consider another option: 
B.3: As Option B.2, but not optionally, this avoids the need of another endpoint (option A), should be applicable at least for none constrained environments ...

**Comment by stfries** [comment]
Regarding the Options 1 and 2, [RFC 7030](https://datatracker.ietf.org/doc/html/rfc7030#section-4.1.3) states that via cacerts a certificate only response is provided. To maek it clear, that we have a wrapped (JWS) cacerts response, option 2 is the better choice
