### ISSUE TITLE
Is "registrar" meant or "registrar-agent" (5.5)

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/anima-brski-prm#40]
> The interaction of the pledge with the registrar-agent may be
>    accomplished using different transport means (protocols and or
>    network technologies).  For this document the usage of HTTP is
>    targeted as in BRSKI.  Alternatives may be CoAP, Bluetooth Low Energy
>    (BLE), or Nearfield Communication (NFC).  This requires independence
>    of the exchanged data objects between the pledge and the registrar
>    from transport security.  Therefore, authenticated self-contained
>    objects (here: signature-wrapped objects) are applied in the data
>    exchange between the pledge and the registrar.

Above here it says "registrar", was "registrar-agent" meant? Or really "registrar" ?
(Since the objects are indirectly exchanged between pledge and registrar of course.)

On the other hand, it talks about BLE/NFC so one could assume "registrar-agent" was meant.

**Comment by stfries** [comment]
The registrar-agent only facilitates the data exchange between the pledge and the registrar. That said, the statement was done underlining the independence from transport security between the pledge and the registrar. If we state registrar-agent instead of registrar, one may deduce, that the protection with transport security is sufficient between the registrar-agent and the registrar, which is not. We would like to have less trust assumptions on the registrar-agent and not make it a trusted intermediate note.  Also, the registrar needs to verify the wrapping signature.
Does this make it clearer?

**Comment by stfries** [comment]
Good proposal, this is actually the bridge which we would like to underline that the transport may be different on the two hops. 
I would take this and close the issue.
