### ISSUE TITLE
special meaning for possession

### ISSUE THREAD

**Issue by siethower** [anima-wg/anima-brski-prm#94]
Comment from Toerless to section 6.3

> 1967       *  Registrar-agent: possesses voucher and LDevID certificate and
>  
> s/possesses/has obtained/
>  
> (we have this special meaning for posesession such as for proof of possession,
>  so i'd avoid it unless it's used in the context of something where you
>  can create proof of possession).

**Comment by stfries** [comment]
Proposal from Toerless to state "obtained" instead of "possesses" seems fine to avoid confusion with "proof of posession"
Can be adopted, in section 6.3 to 
_Registrar-agent: obtained voucher and LDevID certificate (for pledge) and optionally CA certificates._
in section 6.3.6 to 
_Registrar-agent: obtained voucher status and enroll status from pledge._
in section 6.4 to 
_Registrar-agent: possesses LDevID (RegAgt), may have a list of serial numbers of pledges to be queried and a list of corresponding manufacturer trust anchors to be able to verify signatures performed with the IDevID credential._
can be closed
